language: c++
os:
- linux
- osx
compiler:
- gcc
- clang
sudo: required
dist: trusty
before_script:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install qt5; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then CMAKE_ARGS="-DCMAKE_PREFIX_PATH=/usr/local/opt/qt5";
  fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew tap homebrew/science; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install opencv3 --with-contrib --without-eigen
  --without-opencl --without-openexr --without-python --without-tests; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew ln opencv3 --force; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-add-repository -y ppa:beineri/opt-qt551-trusty;
  fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-add-repository -y ppa:sfiel/opencv-read;
  fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y --no-install-recommends
  debhelper cdbs libopencv-dev libopencv-stitching-dev libopencv-imgcodecs-dev libopencv-flann-dev
  libopencv-features2d-dev libopencv-calib3d-dev libopencv-hdf-dev libopencv-reg-dev
  libopencv-shape-dev libopencv-xobjdetect-dev libopencv-xfeatures2d-dev libopencv-ximgproc-dev
  libopencv-highgui-dev cmake qt55tools qt55svg qt55base libtbb-dev libwebp-dev libbz2-dev
  libv4l-dev; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install --yes doxygen graphviz; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then CMAKE_ARGS="-DCMAKE_PREFIX_PATH=/opt/qt55/bin/";
  fi
- mkdir build
- cd build
script:
- cmake $CMAKE_ARGS ../.
- make -j8
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; openssl aes-256-cbc -K $encrypted_528aa76f26bd_key -iv $encrypted_528aa76f26bd_iv
  -in config/travisci_rsa.enc -out config/travisci_rsa -d; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]];; chmod 0600 config/travisci_rsa; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]];; cp config/travisci_rsa ~/.ssh/id_rsa; fi
after_success:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; cd ..; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; ./config/publish-doxygen; fi
