language: c++

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

sudo: required
dist: xenial

before_script:
  # OSX dependencies
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install qt5; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then CMAKE_ARGS="-DCMAKE_PREFIX_PATH=/usr/local/opt/qt5"; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install exiv2; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libraw; fi
  #- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install quazip; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew tap homebrew/science; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install opencv; fi

  # Linux dependencies
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y --no-install-recommends debhelper cdbs qt5-qmake libqt5core5a libqt5widgets5 libqt5network5 libqt5gui5 libqt5printsupport5 libqt5svg5-dev qttools5-dev-tools qttools5-dev qt5-default libexiv2-dev libraw-dev libopencv-dev libhighgui-dev libcvaux-dev cmake libtiff-dev libzip-dev ; fi

  - mkdir build
  - cd build

script:
  - cmake $CMAKE_ARGS ../.
  - make -j8
  
