var _g_coptimization_8h =
[
    [ "GCException", "class_g_c_exception.html", "class_g_c_exception" ],
    [ "GCoptimization", "class_g_coptimization.html", "class_g_coptimization" ],
    [ "DataCostFunctor", "struct_g_coptimization_1_1_data_cost_functor.html", "struct_g_coptimization_1_1_data_cost_functor" ],
    [ "SparseDataCost", "struct_g_coptimization_1_1_sparse_data_cost.html", "struct_g_coptimization_1_1_sparse_data_cost" ],
    [ "SmoothCostFunctor", "struct_g_coptimization_1_1_smooth_cost_functor.html", "struct_g_coptimization_1_1_smooth_cost_functor" ],
    [ "LabelCost", "struct_g_coptimization_1_1_label_cost.html", "struct_g_coptimization_1_1_label_cost" ],
    [ "LabelCostIter", "struct_g_coptimization_1_1_label_cost_iter.html", "struct_g_coptimization_1_1_label_cost_iter" ],
    [ "DataCostFnFromArray", "struct_g_coptimization_1_1_data_cost_fn_from_array.html", "struct_g_coptimization_1_1_data_cost_fn_from_array" ],
    [ "DataCostFnFromFunction", "struct_g_coptimization_1_1_data_cost_fn_from_function.html", "struct_g_coptimization_1_1_data_cost_fn_from_function" ],
    [ "DataCostFnFromFunctionExtra", "struct_g_coptimization_1_1_data_cost_fn_from_function_extra.html", "struct_g_coptimization_1_1_data_cost_fn_from_function_extra" ],
    [ "SmoothCostFnFromArray", "struct_g_coptimization_1_1_smooth_cost_fn_from_array.html", "struct_g_coptimization_1_1_smooth_cost_fn_from_array" ],
    [ "SmoothCostFnFromFunction", "struct_g_coptimization_1_1_smooth_cost_fn_from_function.html", "struct_g_coptimization_1_1_smooth_cost_fn_from_function" ],
    [ "SmoothCostFnFromFunctionExtra", "struct_g_coptimization_1_1_smooth_cost_fn_from_function_extra.html", "struct_g_coptimization_1_1_smooth_cost_fn_from_function_extra" ],
    [ "SmoothCostFnPotts", "struct_g_coptimization_1_1_smooth_cost_fn_potts.html", "struct_g_coptimization_1_1_smooth_cost_fn_potts" ],
    [ "DataCostFnSparse", "class_g_coptimization_1_1_data_cost_fn_sparse.html", "class_g_coptimization_1_1_data_cost_fn_sparse" ],
    [ "iterator", "class_g_coptimization_1_1_data_cost_fn_sparse_1_1iterator.html", "class_g_coptimization_1_1_data_cost_fn_sparse_1_1iterator" ],
    [ "GCoptimizationGridGraph", "class_g_coptimization_grid_graph.html", "class_g_coptimization_grid_graph" ],
    [ "GCoptimizationGeneralGraph", "class_g_coptimization_general_graph.html", "class_g_coptimization_general_graph" ],
    [ "GCO_MAX_ENERGYTERM", "_g_coptimization_8h.html#a7349bb5c933d74d19dd20f4d07578adc", null ],
    [ "OLGA_INLINE", "_g_coptimization_8h.html#afdfe5e97510186657f166dbd7712a6e0", null ],
    [ "gcoclock_t", "_g_coptimization_8h.html#a5ac14b316a2a77b3d443a4032c79a4c2", null ],
    [ "gcoclock", "_g_coptimization_8h.html#a333df2084d7160efd73fac4460d3a833", null ],
    [ "GCO_CLOCKS_PER_SEC", "_g_coptimization_8h.html#a07f7cd2902cd9a889716e51b5c60893d", null ]
];